services:
  db:
    image: mysql:8.0
    networks:
      - service
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 512M

  was:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
    networks:
      - service
    restart: always
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.2'
          memory: 512M
    depends_on:
      - db

  web:
    image: nginx
    ports:
      - "8080:80"
    networks:
      - service
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
    depends_on:
      - db
      - was

networks:
  service:

volumes:
  mysql-volume:
