services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        IMAGE_VERSION: 3.12-alpine
    deploy:
      replicas: 1 # 컨테이너 갯수
      resources: # 사용 가능한 자원 제한
        limits:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: any # none, on-failure(max_attempts)
        # max_attempts: 3 # 최대 시도 횟수, window 값 내에서의 실패는 횟수 차감 X
    ports:
      - "8000:5000"
    stop_signal: SIGINT # flask는 SIGINT를 받으면 gracefully shutdown 진행
    depends_on:
      - redis # redis 서비스가 running 상태가 되면 web 서비스 시작

  redis:
    image: "redis:alpine"